# Generated by Django 2.1.5 on 2019-02-07 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20190207_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('nummero', models.CharField(max_length=20)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='tel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='doc',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, to='clientes.DOC'),
            preserve_default=False,
        ),
    ]
