# Generated by Django 2.1.5 on 2019-02-07 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20190207_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
        ),
    ]
