# Generated by Django 2.1.5 on 2019-02-07 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20190207_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='numero',
            new_name='num',
        ),
        migrations.AlterField(
            model_name='tel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
        ),
    ]
