# Generated by Django 2.1.5 on 2019-02-07 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20190207_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomdepart', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='tel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='depart',
            field=models.ManyToManyField(to='clientes.Depart'),
        ),
    ]
